"""autogenerated by genpy from ublox/raw.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ublox.msg
import std_msgs.msg

class raw(genpy.Message):
  _md5sum = "adf036c089e10cedb0284b01bd41ad77"
  _type = "ublox/raw"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

# RXM-RAW

rawmeasreap[32] RawMeasReap
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: ublox/rawmeasreap
# RawMeasReap

float64 cpmeas      # cycles - Carrier Phase measurement
float64 prmeas    # m - Psuedorange measurement
float64 domeas       # Hz - Doppler Measurement
float64 svid       # SV Number
float64 measqual    # Nav Measurement Quality Indicator  -- (>=4 PR+DO OK) (>=5 PR+DO+CP OK) (<6 likel loss carrier lock)
float64 cnratio     # dbHz - Carrier to Noise Ratio
float64 lli        # Loss of Lock Indicator (RINEX Definition)
"""
  __slots__ = ['header','RawMeasReap']
  _slot_types = ['std_msgs/Header','ublox/rawmeasreap[32]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,RawMeasReap

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(raw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.RawMeasReap is None:
        self.RawMeasReap = [ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap()]
    else:
      self.header = std_msgs.msg.Header()
      self.RawMeasReap = [ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap(),ublox.msg.rawmeasreap()]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      for val1 in self.RawMeasReap:
        _x = val1
        buff.write(_struct_7d.pack(_x.cpmeas, _x.prmeas, _x.domeas, _x.svid, _x.measqual, _x.cnratio, _x.lli))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.RawMeasReap is None:
        self.RawMeasReap = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      self.RawMeasReap = []
      for i in range(0, 32):
        val1 = ublox.msg.rawmeasreap()
        _x = val1
        start = end
        end += 56
        (_x.cpmeas, _x.prmeas, _x.domeas, _x.svid, _x.measqual, _x.cnratio, _x.lli,) = _struct_7d.unpack(str[start:end])
        self.RawMeasReap.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      for val1 in self.RawMeasReap:
        _x = val1
        buff.write(_struct_7d.pack(_x.cpmeas, _x.prmeas, _x.domeas, _x.svid, _x.measqual, _x.cnratio, _x.lli))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.RawMeasReap is None:
        self.RawMeasReap = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      self.RawMeasReap = []
      for i in range(0, 32):
        val1 = ublox.msg.rawmeasreap()
        _x = val1
        start = end
        end += 56
        (_x.cpmeas, _x.prmeas, _x.domeas, _x.svid, _x.measqual, _x.cnratio, _x.lli,) = _struct_7d.unpack(str[start:end])
        self.RawMeasReap.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
