(cl:in-package ublox-msg)
(cl:export '(PRN-VAL
          PRN
          TOW-VAL
          TOW
          HEALTH-VAL
          HEALTH
          IODE1-VAL
          IODE1
          IODE2-VAL
          IODE2
          WEEK-VAL
          WEEK
          ZWEEK-VAL
          ZWEEK
          TOE-VAL
          TOE
          MAJAXIS-VAL
          MAJAXIS
          DN-VAL
          DN
          ANRTIME-VAL
          ANRTIME
          ECC-VAL
          ECC
          OMEGA-VAL
          OMEGA
          CUC-VAL
          CUC
          CUS-VAL
          CUS
          CRC-VAL
          CRC
          CRS-VAL
          CRS
          CIC-VAL
          CIC
          CIS-VAL
          CIS
          IA-VAL
          IA
          DIA-VAL
          DIA
          WO-VAL
          WO
          DWO-VAL
          DWO
          IODC-VAL
          IODC
          TOC-VAL
          TOC
          TGD-VAL
          TGD
          AF0-VAL
          AF0
          AF1-VAL
          AF1
          AF2-VAL
          AF2
          CMOT-VAL
          CMOT
          URA-VAL
          URA
))