/* Auto-generated by genmsg_cpp for file /home/cody/Development/DR_ws/ublox/msg/navSol.msg */
#ifndef UBLOX_MESSAGE_NAVSOL_H
#define UBLOX_MESSAGE_NAVSOL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ublox
{
template <class ContainerAllocator>
struct navSol_ {
  typedef navSol_<ContainerAllocator> Type;

  navSol_()
  {
  }

  navSol_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::ublox::navSol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ublox::navSol_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct navSol
typedef  ::ublox::navSol_<std::allocator<void> > navSol;

typedef boost::shared_ptr< ::ublox::navSol> navSolPtr;
typedef boost::shared_ptr< ::ublox::navSol const> navSolConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ublox::navSol_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ublox::navSol_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ublox

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ublox::navSol_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ublox::navSol_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ublox::navSol_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::ublox::navSol_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ublox::navSol_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ublox/navSol";
  }

  static const char* value(const  ::ublox::navSol_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ublox::navSol_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::ublox::navSol_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ublox::navSol_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ublox::navSol_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct navSol_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ublox::navSol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ublox::navSol_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // UBLOX_MESSAGE_NAVSOL_H

