/* Auto-generated by genmsg_cpp for file /home/cody/Development/DR_ws/ublox/msg/Velned.msg */
#ifndef UBLOX_MESSAGE_VELNED_H
#define UBLOX_MESSAGE_VELNED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace ublox
{
template <class ContainerAllocator>
struct Velned_ {
  typedef Velned_<ContainerAllocator> Type;

  Velned_()
  : header()
  , VelN(0.0)
  , VelE(0.0)
  , VelD(0.0)
  , speed(0.0)
  , heading(0.0)
  {
  }

  Velned_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , VelN(0.0)
  , VelE(0.0)
  , VelD(0.0)
  , speed(0.0)
  , heading(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _VelN_type;
  double VelN;

  typedef double _VelE_type;
  double VelE;

  typedef double _VelD_type;
  double VelD;

  typedef double _speed_type;
  double speed;

  typedef double _heading_type;
  double heading;


  typedef boost::shared_ptr< ::ublox::Velned_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ublox::Velned_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Velned
typedef  ::ublox::Velned_<std::allocator<void> > Velned;

typedef boost::shared_ptr< ::ublox::Velned> VelnedPtr;
typedef boost::shared_ptr< ::ublox::Velned const> VelnedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ublox::Velned_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ublox::Velned_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ublox

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ublox::Velned_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ublox::Velned_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ublox::Velned_<ContainerAllocator> > {
  static const char* value() 
  {
    return "419f63ee0c2216bb14c9ae2b69909746";
  }

  static const char* value(const  ::ublox::Velned_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x419f63ee0c2216bbULL;
  static const uint64_t static_value2 = 0x14c9ae2b69909746ULL;
};

template<class ContainerAllocator>
struct DataType< ::ublox::Velned_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ublox/Velned";
  }

  static const char* value(const  ::ublox::Velned_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ublox::Velned_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# Velocity and Heading\n\
float64 VelN\n\
float64 VelE\n\
float64 VelD\n\
\n\
float64 speed\n\
\n\
float64 heading\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::ublox::Velned_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ublox::Velned_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ublox::Velned_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ublox::Velned_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.VelN);
    stream.next(m.VelE);
    stream.next(m.VelD);
    stream.next(m.speed);
    stream.next(m.heading);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Velned_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ublox::Velned_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ublox::Velned_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "VelN: ";
    Printer<double>::stream(s, indent + "  ", v.VelN);
    s << indent << "VelE: ";
    Printer<double>::stream(s, indent + "  ", v.VelE);
    s << indent << "VelD: ";
    Printer<double>::stream(s, indent + "  ", v.VelD);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UBLOX_MESSAGE_VELNED_H

